import './style.css';
import { GpuWorld } from './gpu.ts';
import { createWorldGrid } from './full-world.ts';
import { makeParams, validateParams } from './generation/params.ts';
import { lightDriftVelocity, sunRhythmAt } from './generation/light.ts';
import { createGrid, SCENES, type Scene } from './model.ts';
import { encodeCheckpoint, decodeCheckpoint, type Checkpoint } from './checkpoint.ts';
import { Panel, SPEEDS, SPEED_KEYS } from './legacy/panel.ts';
import { CoordinateRulers } from './legacy/rulers.ts';
import { WorldSummary } from './legacy/summary.ts';
import { formatMass, formatLength, formatNumber, formatPercent, formatDuration, formatWorldAge } from './legacy/units.ts';
import { checkInspector } from './inspector-checks.ts';
import { checkCheckpoint } from './checkpoint-checks.ts';
import { runChecks } from './checks.ts';
const node=<T extends Element = HTMLElement>(selector:string)=>document.querySelector<T>(selector)!;
const app=node('.app'),canvas=node<HTMLCanvasElement>('#world'),stage=node('.stage'),mini=node<HTMLCanvasElement>('.minimap');
const summary=new WorldSummary(node('#world-summary'));
const camera={x:.5,y:.5,zoom:1,layer:0};
let gpu:GpuWorld|null=null,params=makeParams(),paused=true,busy=true,speed=1,debt=0,actualRate=0,fps:number|null=null,visualTime=0;
let checkpoint:Checkpoint|null=null,lastCheckpoint=0,advance=Promise.resolve(),reading=false,lastRead=0,epoch=0;
let point:{x:number;y:number}|null=null,pinned=false,pointVersion=0,pointPending=false,lastPoint=0;
let latestStep=0,rulers=false,scene:Scene='world',resolution=128;
const marker=document.createElement('div');marker.className='gpu-probe';marker.hidden=true;stage.append(marker);
const rulerCanvas=document.createElement('canvas');rulerCanvas.className='gpu-ruler-overlay';stage.append(rulerCanvas);const coordinates=new CoordinateRulers(canvas);const rulerContext=rulerCanvas.getContext('2d')!;
node('.mineral-stats').innerHTML='<details class="mineral-details"><summary><b>Минерал</b><span class="mineral-scale"><span class="mineral-bar" role="img"><i class="depths"></i><i class="out"></i><i class="deposits"></i><i class="medium"></i><i class="threshold"></i></span><span class="mineral-ticks"><span class="mass-zero"></span><span class="mass-half"></span><span class="mass-total"></span></span></span></summary><div class="mineral-keys"><span class="key"><i class="depths"></i>недра <span class="amount-depths"></span></span><span class="key"><i class="deposits"></i>залежи <span class="amount-deposits"></span></span><span class="key"><i class="medium"></i>растворено <span class="amount-medium"></span></span><span class="key"><i class="out"></i>в полёте <span class="amount-out"></span></span><span class="volcanoes"></span></div></details>';
const panel=new Panel({app,toolbar:node('#toolbar'),params:node('#params'),legend:node('#legend'),tip:node('.tip'),observation:node('#observation'),summary:node('#world-summary'),navigation:node('#navigation'),viewControls:node('#view-controls')},params,{
 onLayoutChange:()=>{},onCreate:p=>{params=p;scene='world';void reset();},onTogglePause:()=>{if(!busy){paused=!paused;debt=0;}},onUnpinProbe:()=>{pinned=false;pointVersion++;panel.setProbePinned(false);},onSpeed:s=>{speed=s;debt=0;},onSave:()=>{void save();},onLoad:file=>{void load(file);},onZoomIn:()=>zoom(1.5),onZoomOut:()=>zoom(1/1.5),onZoomFit:()=>{Object.assign(camera,{x:.5,y:.5,zoom:1});},onProcesses:enabled=>{camera.layer=enabled?3:0;},onRulers:enabled=>{rulers=enabled;coordinates.toggle(enabled);}
});
// Identical mineral scale and keys; flight and reservations follow the GPU ownership model.

const diagnostics=document.createElement('details');diagnostics.className='gpu-diagnostics';diagnostics.innerHTML=`<summary>Диагностика GPU-кандидата</summary><label>Сцена <select id="gpu-scene">${Object.entries(SCENES).map(([id,label])=>`<option value="${id}">${label}</option>`).join('')}</select></label><label>Сетка <select id="gpu-grid"><option value="128">128</option><option value="256">256</option></select></label><label>Карта <select id="gpu-layer"><option value="0">Мир</option><option value="1">Свет</option><option value="2">Минерал</option><option value="3">Скорость</option><option value="4">Температура</option></select></label><button id="gpu-inspector-check">Проверить инспектор</button><button id="gpu-save-check">Проверить сохранение</button><button id="gpu-physics-check">Проверить физику</button><pre id="gpu-report"></pre>`;node('#params').append(diagnostics);
node<HTMLSelectElement>('#gpu-scene').onchange=e=>{scene=(e.target as HTMLSelectElement).value as Scene;void reset();};node<HTMLSelectElement>('#gpu-grid').onchange=e=>{resolution=Number((e.target as HTMLSelectElement).value);void reset();};node<HTMLSelectElement>('#gpu-layer').onchange=e=>{camera.layer=Number((e.target as HTMLSelectElement).value);};
const fail=(error:unknown)=>{paused=true;busy=true;debt=0;panel.setFileStatus([error instanceof Error?error.message:String(error)],true);};
let resetting=false;async function reset(){if(!gpu||resetting)return;resetting=true;busy=true;paused=true;debt=0;epoch++;try{await advance;const errors=validateParams(params);if(errors.length)throw new Error(errors.join('\n'));await gpu.reset(scene==='world'?createWorldGrid(params,resolution):createGrid(scene,resolution));latestStep=0;checkpoint=await gpu.checkpoint();lastCheckpoint=performance.now();panel.setCurrent(params);document.title=`GPU-кандидат · сид ${params.seed}`;history=[];point=null;pinned=false;pointVersion++;panel.setProbePinned(false);panel.setProbe(null);busy=false;panel.setFileStatus(['GPU-кандидат · основной старый мир остаётся на порту 5173'],false);await observations();}catch(error){fail(error);}finally{resetting=false;}}
async function save(){if(!gpu||busy)return;paused=true;busy=true;debt=0;try{await advance;checkpoint=await gpu.checkpoint();const text=encodeCheckpoint(checkpoint),url=URL.createObjectURL(new Blob([text],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=`ecobugs-gpu-${params.seed}-step-${gpu.step}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);busy=false;panel.setFileStatus([`Сохранён GPU-мир на шаге ${gpu.step.toLocaleString('ru')}`],false);}catch(error){fail(error);}}
async function load(file:File){if(!gpu||busy)return;let backup:Checkpoint|null=null,mutated=false;try{if(file.size>384*1024*1024)throw new Error('Файл превышает 384 МиБ');const saved=decodeCheckpoint(await file.text());paused=true;busy=true;debt=0;epoch++;await advance;backup=await gpu.checkpoint();mutated=true;await gpu.restore(saved);checkpoint=saved;latestStep=gpu.step;params=saved.grid.params??makeParams();scene=saved.grid.scene;resolution=saved.grid.cols;panel.setCurrent(params);document.title=`GPU-кандидат · сид ${params.seed}`;history=[];point=null;pinned=false;pointVersion++;panel.setProbePinned(false);panel.setProbe(null);busy=false;panel.setFileStatus([`Загружен GPU-мир: шаг ${gpu.step.toLocaleString('ru')}`],false);await observations();}catch(error){if(mutated&&backup){try{await gpu.restore(backup);busy=false;}catch(rollback){fail(rollback);}}else busy=false;panel.setFileStatus([`Мир не загружен: ${error instanceof Error?error.message:String(error)}`],true);}}
for(const [selector,check] of [['#gpu-inspector-check',()=>checkInspector(gpu!)],['#gpu-save-check',async()=>{const result=await checkCheckpoint(gpu!, text=>{node("#gpu-report").textContent=text;});gpu=result.gpu;return result.report;}],['#gpu-physics-check',()=>runChecks(gpu!, text=>{node("#gpu-report").textContent=text;})]] as const)node<HTMLButtonElement>(selector).onclick=()=>{if(busy||!gpu)return;busy=true;paused=true;epoch++;void (async()=>{try{await advance;node('#gpu-report').textContent=await check();await reset();}catch(error){fail(error);}})();};
function bound(){const half=.5/camera.zoom;camera.x=Math.max(half,Math.min(1-half,camera.x));camera.y=Math.max(half,Math.min(1-half,camera.y));}
function zoom(factor:number,anchor={x:.5,y:.5}){const before=camera.zoom;camera.zoom=Math.max(1,Math.min(16,before*factor));camera.x+=(anchor.x-.5)*(1/before-1/camera.zoom);camera.y+=(anchor.y-.5)*(1/before-1/camera.zoom);bound();}
const local=(x:number,y:number)=>{const r=canvas.getBoundingClientRect();return {x:(x-r.left)/r.width,y:(y-r.top)/r.height};};
canvas.onwheel=e=>{e.preventDefault();const r=canvas.getBoundingClientRect(),wheel=e.deltaMode===1||e.deltaX===0&&Number.isInteger(e.deltaY)&&Math.abs(e.deltaY)>=40;if(e.ctrlKey||wheel)zoom(Math.exp(-e.deltaY*(e.deltaMode===1?.05:.002)),local(e.clientX,e.clientY));else{camera.x+=e.deltaX/r.width/camera.zoom;camera.y+=e.deltaY/r.height/camera.zoom;bound();}};
let dragging:{id:number;x:number;y:number;startX:number;startY:number;moved:boolean}|null=null;
canvas.onpointerdown=e=>{if(e.button!==0)return;canvas.setPointerCapture(e.pointerId);dragging={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};};
canvas.onpointermove=e=>{const r=canvas.getBoundingClientRect();if(dragging&&dragging.id===e.pointerId){if(Math.hypot(e.clientX-dragging.startX,e.clientY-dragging.startY)>4)dragging.moved=true;if(dragging.moved){camera.x-=(e.clientX-dragging.x)/r.width/camera.zoom;camera.y-=(e.clientY-dragging.y)/r.height/camera.zoom;bound();}dragging.x=e.clientX;dragging.y=e.clientY;}if(!pinned&&!dragging?.moved){const p=local(e.clientX,e.clientY);point={x:camera.x+(p.x-.5)/camera.zoom,y:camera.y+(p.y-.5)/camera.zoom};pointVersion++;}};
canvas.onpointerup=e=>{if(dragging?.id===e.pointerId){if(!dragging.moved){const p=local(e.clientX,e.clientY);point={x:camera.x+(p.x-.5)/camera.zoom,y:camera.y+(p.y-.5)/camera.zoom};pinned=true;pointVersion++;panel.setProbePinned(true);}dragging=null;}};canvas.onpointercancel=()=>{dragging=null;};canvas.ondblclick=e=>zoom(1.5,local(e.clientX,e.clientY));
mini.onclick=e=>{const r=mini.getBoundingClientRect();camera.x=(e.clientX-r.left)/r.width;camera.y=(e.clientY-r.top)/r.height;bound();};
document.addEventListener('keydown',e=>{if((e.target as HTMLElement).closest('input,select,textarea,[contenteditable=true]'))return;const key=e.key.toLowerCase();if(key===' '){if(e.target instanceof HTMLButtonElement)return;e.preventDefault();if(!busy){paused=!paused;debt=0;}}if(key==='+'||key==='=')zoom(1.5);if(key==='-')zoom(1/1.5);if(key==='0')Object.assign(camera,{x:.5,y:.5,zoom:1});const index=SPEED_KEYS.indexOf(key);if(index>=0){speed=SPEEDS[index];debt=0;}if(key==='escape'){pinned=false;pointVersion++;panel.setProbePinned(false);panel.closePanels();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){paused=true;debt=0;}});
const signedMass=(value:number)=>(value<0?'−':'')+formatMass(Math.abs(value));
type History={step:number;shares:number[];depths:number;medium:number;deposits:number;eruptions:number;emitted:number;captured:number};let history:History[]=[];
async function observations(){if(!gpu||busy||reading)return;reading=true;const world=gpu,ownEpoch=epoch;try{const m=await world.summary(),o=await world.observe();if(gpu!==world||ownEpoch!==epoch||busy)return;const q=world.grid.quantum??.001,depths=(m.available+m.reserved+m.captured)*q,medium=(m.dissolved+m.flying)*q,deposits=m.deposits*q,out=m.flying*q,total=depths+medium+deposits;
 const parts=[depths,out,deposits,m.dissolved*q];let left=0;for(const [i,name]of ['depths','out','deposits','medium'].entries()){const width=total?parts[i]/total*100:0;const bar=node<HTMLElement>(`.mineral-bar .${name}`);bar.style.left=`${left}%`;bar.style.width=`${width}%`;left+=width;node(`.amount-${name}`).textContent=formatMass(parts[i]);}
 node('.mass-zero').textContent=formatMass(0);node('.mass-half').textContent=formatMass(total/2);node('.mass-total').textContent=formatMass(total);const threshold=(world.sources?.threshold??0)*q;node<HTMLElement>('.mineral-bar .threshold').style.left=`${total?threshold/total*100:0}%`;node('.mineral-bar').setAttribute('aria-label',`Минерал без грунта: ${formatMass(total)}; недра ${formatMass(depths)}; залежи ${formatMass(deposits)}; растворено ${formatMass(m.dissolved*q)}; в полёте ${formatMass(out)}. Резерв извержения включён в недра.`);node('.volcanoes').textContent=`Вулканы ${world.sources?.volcanoes.length??0} · извержений ${world.sources?.eruptions??0}`;
 const current:History={step:m.step,shares:o.shares,depths,medium,deposits,eruptions:world.sources?.eruptions??0,emitted:o.emitted,captured:o.captured};if(history.at(-1)?.step!==m.step)history.push(current);while(history.length>2&&history[1].step<=m.step-600)history.shift();const before=history[0];
 summary.render({size:`${formatLength(world.grid.width)} × ${formatLength(world.grid.height)}`,area:`${formatNumber(world.grid.width*world.grid.height*(world.grid.shape==='circle'?Math.PI/4:1)/1e6)} м²`,age:formatWorldAge(m.step),water:formatPercent(o.shares[0]),shallows:formatPercent(o.shares[1]),land:formatPercent(o.shares[2]),total:formatMass(total),depths:formatMass(depths),medium:formatMass(medium),deposits:formatMass(deposits),transit:formatMass(out),volcanoes:`${world.sources?.volcanoes.filter(v=>v.stage==='erupting').length??0} извергаются · ${world.sources?.volcanoes.filter(v=>v.stage==='preparing').length??0} готовятся`,funnels:String(world.funnels?.active.length??0),movements:`${world.geology?.active.filter(v=>!v.quake).length??0} / ${world.geology?.active.filter(v=>v.quake).length??0}`,flow:`≈ ${formatNumber(o.averageSpeed)} мм/с`,period:`За ${formatDuration(m.step-before.step)}`,deltaWater:`${formatNumber((o.shares[0]-before.shares[0])*100)} п.п.`,deltaShallows:`${formatNumber((o.shares[1]-before.shares[1])*100)} п.п.`,deltaLand:`${formatNumber((o.shares[2]-before.shares[2])*100)} п.п.`,deltaDepths:signedMass(depths-before.depths),deltaMedium:signedMass(medium-before.medium),deltaDeposits:signedMass(deposits-before.deposits),deltaEruptions:String(current.eruptions-before.eruptions),emitted:formatMass(o.emitted-before.emitted),funnelSunk:formatMass(o.captured-before.captured)},m.step);
 if(m.massError||m.flightOverflow||m.reservoirError)throw new Error('Нарушен баланс или расчёт вещества');
 }catch(error){if(ownEpoch===epoch)fail(error);}finally{reading=false;}}
async function inspect(now:number){if(!gpu||busy||!point||pointPending||now-lastPoint<250||node<HTMLDetailsElement>('#probe-section').hidden)return;pointPending=true;lastPoint=now;const world=gpu,ownEpoch=epoch,version=pointVersion,p={...point};try{const sample=await world.inspect(p.x,p.y);if(gpu!==world||epoch!==ownEpoch||version!==pointVersion||busy)return;const outside=p.x<0||p.x>1||p.y<0||p.y>1||(world.grid.shape==='circle'&&Math.hypot(p.x-.5,p.y-.5)>.5);const lines=[`Координаты: ${formatLength(p.x*world.grid.width)} / ${formatLength(p.y*world.grid.height)}`,`Местность: ${outside?'вне чашки':sample.blocked?'перегородка':sample.hole?'отверстие':sample.grade<.5?'вода':sample.grade<1.5?'отмель':'суша'}`];if(!outside&&!sample.blocked)lines.push(`Минерал: ${formatNumber(sample.mineral*1000)} г/м²`,`Залежи: ${formatNumber(sample.deposits*1000)} г/м²`,`Свет: ${formatNumber(sample.light)}`,`Температура: ${formatNumber(sample.temperature)}`,`Течение: ${formatNumber(Math.hypot(sample.vx,sample.vy))} мм/с`,`Вектор: ${formatNumber(sample.vx)} / ${formatNumber(sample.vy)} мм/с`,`Шаг: ${sample.step.toLocaleString('ru')}`);const volcano=world.sources?.volcanoes.find(v=>v.cell===sample.cell),funnel=world.funnels?.active.find(v=>v.area.includes(sample.cell));if(volcano)lines.push(`Вулкан #${volcano.id}: ${({preparing:'подготовка',erupting:'извержение',sleeping:'сон',fading:'затухание'})[volcano.stage]}`);if(funnel)lines.push(`Воронка #${funnel.id}: ${formatPercent(funnel.strength)}`);panel.setProbe(lines);}catch(error){if(ownEpoch===epoch)panel.setProbe([`Наблюдение недоступно: ${String(error)}`]);}finally{pointPending=false;}}
let lastTime=performance.now(),rateStart=lastTime,rateStep=0,frames=0;
async function frame(now:number){const elapsed=Math.min(.1,(now-lastTime)/1000);lastTime=now;try{if(gpu&&!busy&&!document.hidden){if(gpu.lost||gpu.errors.length)throw new Error(gpu.errors.join('\n')||'Устройство GPU потеряно');if(!paused){debt+=elapsed*10*speed;const steps=Math.min(32,Math.floor(debt));advance=(async()=>{const done=await gpu!.advanceBatch(steps,()=>!paused&&!busy);debt=paused||busy?0:Math.min(32,debt-done);})();await advance;}if(!busy){await gpu.device.queue.onSubmittedWorkDone();latestStep=gpu.step;const aspect=gpu.grid.cols/gpu.grid.rows,w=Math.max(1,Math.min(stage.clientWidth-(rulers?28:0)-52,(stage.clientHeight-(rulers?24:0)-52)*aspect));canvas.dataset.fitted=String(camera.zoom===1);canvas.style.width=`${w}px`;canvas.style.height=`${w/aspect}px`;if(!paused)visualTime+=elapsed;gpu.draw(false,camera,undefined,visualTime);if(!node<HTMLDetailsElement>('#navigation').hidden&&node<HTMLDetailsElement>('#navigation').open){mini.style.height='auto';gpu.draw(false,{x:.5,y:.5,zoom:1,layer:0},mini,visualTime);}panel.setZoom(camera.zoom);const cr=canvas.getBoundingClientRect(),sr=stage.getBoundingClientRect();rulerCanvas.style.left=`${cr.left-sr.left}px`;rulerCanvas.style.top=`${cr.top-sr.top}px`;rulerCanvas.style.width=`${cr.width}px`;rulerCanvas.style.height=`${cr.height}px`;rulerCanvas.width=canvas.width;rulerCanvas.height=canvas.height;coordinates.draw(rulerContext,{shape:gpu.grid.shape??'rectangle',width:gpu.grid.width,height:gpu.grid.height,area:gpu.grid.width*gpu.grid.height},canvas.width/gpu.grid.width*camera.zoom,camera.x*gpu.grid.width,camera.y*gpu.grid.height,canvas.width/cr.width);if(point&&pinned){const r=canvas.getBoundingClientRect(),s=stage.getBoundingClientRect(),x=(point.x-camera.x)*camera.zoom+.5,y=(point.y-camera.y)*camera.zoom+.5;marker.hidden=x<0||x>1||y<0||y>1;marker.style.left=`${r.left-s.left+x*r.width}px`;marker.style.top=`${r.top-s.top+y*r.height}px`;}else marker.hidden=true;
 const map=gpu.grid.lightMap;if(map){const [vx,vy]=lightDriftVelocity(map,gpu.step);node<SVGElement>('.light-drift svg').style.transform=`rotate(${Math.atan2(vy,vx)}rad)`;node('.sun-rhythm').textContent=`солнце ×${formatNumber(sunRhythmAt(map,gpu.step))}`;}
 void inspect(now);if(now-lastRead>1000){lastRead=now;void observations();}if(!paused&&now-lastCheckpoint>15000){checkpoint=await gpu.checkpoint();lastCheckpoint=now;}frames++;const seconds=(now-rateStart)/1000;if(seconds>=1){fps=frames/seconds;actualRate=Math.max(0,latestStep-rateStep)/seconds;rateStep=latestStep;rateStart=now;frames=0;}}}panel.setTime(latestStep,paused,speed,fps,actualRate,!paused&&actualRate<speed*8);}catch(error){fail(error);}requestAnimationFrame(time=>{void frame(time);});}
void GpuWorld.create(canvas).then(async world=>{gpu=world;await reset();}).catch(fail);requestAnimationFrame(time=>{void frame(time);});
